repos:
  - repo: local
    hooks:
      - id: remark
        name: remark
        entry: npx remark --quiet --frail
        language: node
        types: [markdown]
        additional_dependencies: [remark-cli]
